---
driver:
  name: ssh
  hostname: 10.0.0.1
  port: 22
  username: root
  ssh_key: /Users/rlupo/.ssh/rlupo_aws_sa.pem

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[desjardins::default]
    attributes:
