---
driver:
  name: ssh
  hostname: 52.90.137.115
  port: 22
  username: ec2-user
  ssh_key: /Users/rlupo/.ssh/rlupo_aws_sa.pem

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: solaris10
    driver:
      hostname: 52.90.137.115

  - name: solaris11
    driver:
      hostname: 52.90.137.115
      
suites:
  - name: default
    run_list:
      - recipe[desjardins::default]
    attributes:
