name 'desjardins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures desjardins'
long_description 'Installs/Configures desjardins'
version '0.1.1'
